language: node_js
node_js:
  - "stable"

before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get upgrade libstdc++6 -y
- cd $HOME
- curl -LO https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
- tar -xf emsdk-portable.tar.gz
- cd emsdk-portable
- ./emsdk update
- ./emsdk install latest
- ./emsdk activate latest
- source ./emsdk_env.sh
- cd $TRAVIS_BUILD_DIR

install:
- yarn

script:
- yarn test