language: node_js
node_js:
  - "stable"
dist: "xenial"

before_install:
- sudo apt-get update
- sudo apt-get upgrade --no-install-recommends --no-install-suggests libstdc++6 -y
- cd $HOME
- curl -LO https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
- tar -xf emsdk-portable.tar.gz
- cd emsdk-portable
- ./emsdk update
- ./emsdk install latest
- ./emsdk activate latest
- source ./emsdk_env.sh
- cd $TRAVIS_BUILD_DIR

install:
- yarn

script:
- yarn test